package util;

import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import domain.report.ReportDocument;
import service.exception.PersistenceException;
import service.security.Permission;
import service.security.RbacGuard;
import service.security.Session;

import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

/**
 * Exports a {@link ReportDocument} to a PDF that reproduces the on-screen report exactly, under a
 * header carrying the title, the generating user, the generation timestamp, and the applied
 * parameters (FR-30).
 *
 * <p>Consumes the same neutral document the view renders, so the export cannot drift from what was
 * displayed. Guarded by {@code EXPORT_REPORTS} (Manager/Administrator). No {@code javafx.*}
 * (Principle I) — the bytes back both a desktop save and a future web download.
 */
public final class ReportExporter {

    private static final DateTimeFormatter STAMP = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    /**
     * Renders the report to PDF bytes.
     *
     * @throws service.exception.AuthorizationException if the session lacks {@code EXPORT_REPORTS}
     */
    public byte[] export(Session session, ReportDocument report) {
        RbacGuard.require(session, Permission.EXPORT_REPORTS);
        if (report == null) {
            throw new PersistenceException("There is no report to export.", null);
        }

        Document document = new Document(PageSize.A4, 36, 36, 48, 36);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter.getInstance(document, out);
            document.open();
            writeHeader(document, session, report);
            for (ReportDocument.Section section : report.getSections()) {
                writeSection(document, section);
            }
            writeSummary(document, report.getSummary());
            document.close();
        } catch (RuntimeException e) {
            throw new PersistenceException("The report could not be exported.", e);
        }
        return out.toByteArray();
    }

    private void writeHeader(Document doc, Session session, ReportDocument report) {
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
        Font metaFont = FontFactory.getFont(FontFactory.HELVETICA, 9);

        add(doc, paragraph("Golden Fork — " + report.getTitle(), titleFont));
        String who = session.getUser() == null ? "-" : session.getUser().getFullName();
        add(doc, paragraph("Generated by: " + who, metaFont));
        add(doc, paragraph("Generated at: " + STAMP.format(LocalDateTime.now()), metaFont));
        for (Map.Entry<String, String> param : report.getParameters().entrySet()) {
            add(doc, paragraph(param.getKey() + ": " + param.getValue(), metaFont));
        }
        add(doc, spacer());
    }

    private void writeSection(Document doc, ReportDocument.Section section) {
        Font headingFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
        Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 9);
        Font headFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9);

        add(doc, paragraph(section.getHeading(), headingFont));

        List<String> columns = section.getColumns();
        PdfPTable table = new PdfPTable(columns.size());
        table.setWidthPercentage(100);
        for (String column : columns) {
            table.addCell(headerCell(column, headFont));
        }
        if (section.getRows().isEmpty()) {
            PdfPCell empty = new PdfPCell(new Phrase("(no rows)", cellFont));
            empty.setColspan(columns.size());
            table.addCell(empty);
        } else {
            for (List<String> row : section.getRows()) {
                for (String value : row) {
                    table.addCell(new PdfPCell(new Phrase(value == null ? "" : value, cellFont)));
                }
            }
        }
        addTable(doc, table);
        add(doc, spacer());
    }

    private void writeSummary(Document doc, List<String> summary) {
        if (summary.isEmpty()) return;
        Font headingFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
        Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 10);
        add(doc, paragraph("Summary", headingFont));
        for (String line : summary) {
            add(doc, paragraph(line, bodyFont));
        }
    }

    private static PdfPCell headerCell(String text, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setGrayFill(0.9f);
        return cell;
    }

    private static Paragraph paragraph(String text, Font font) {
        Paragraph p = new Paragraph(text, font);
        p.setLeading(14f);
        return p;
    }

    private static Paragraph spacer() {
        Paragraph p = new Paragraph(" ");
        p.setLeading(8f);
        return p;
    }

    private static void add(Document doc, Paragraph p) {
        try {
            doc.add(p);
        } catch (Exception e) {
            throw new PersistenceException("The report could not be written.", e);
        }
    }

    private static void addTable(Document doc, PdfPTable table) {
        try {
            doc.add(table);
        } catch (Exception e) {
            throw new PersistenceException("The report table could not be written.", e);
        }
    }
}
